appointer/urls.py
from django.urls import path

from .views import views, signup_views, event_views

app_name = "appointer"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", event_views.EventDetailView.as_view(), name="event_detail"),
    path("<int:event_id>/signup/", signup_views.signup, name="signup"),
    path("<int:event_id>/signout/<int:signout_id>", signup_views.signout, name="signout"),
    path("add/", event_views.add_event, name="add_event"),
    path("<int:event_id>/delete_event/", event_views.delete_event, name="delete_event"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("appointer/", include("appointer.urls")),
]

appointer/models.py
from django.db import models


class Event(models.Model):
    name = models.CharField(max_length=200)
    start_timestamp = models.DateTimeField()
    end_timestamp = models.DateTimeField()

    def __str__(self):
        return f"{self.name} @ {self.start_timestamp}"


class Signup(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} for {self.event.name}"

appointer/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Event, Signup

class IndexView(generic.ListView):
    template_name = "appointer/index.html"
    context_object_name = "upcoming_events_list"

    def get_queryset(self):
        now = timezone.now()
        return Event.objects.filter(end_timestamp__gte=now).order_by("start_timestamp")[:5]


class EventDetailView(generic.DetailView):
    model = Event
    template_name = "appointer/event_detail.html"


def signup(request: HttpRequest, event_id: int):
    event = get_object_or_404(Event, pk=event_id)
    name_in_form = request.POST["new_signup"]
    if not name_in_form.strip():
        return HttpResponseBadRequest(reason="No name provided")
    else:
        signup_instance = Signup(event=event, name=name_in_form)
        signup_instance.save()
        return HttpResponseRedirect(reverse("appointer:event_detail", args=(event.id,)))


def signout(request: HttpRequest, event_id: int, signout_id: int):
    event = get_object_or_404(Event, pk=event_id)

    signup_instance = Signup.objects.get(id=signout_id)
    signup_instance.delete()
    return HttpResponseRedirect(reverse("appointer:event_detail", args=(event.id,)))


def add_event(request: HttpRequest):
    if request.method == 'POST':
        print(request.POST["event_start_timestamp"])
        start_timestamp = request.POST["event_start_timestamp"] # TODO Make timezone aware
        end_timestamp = request.POST["event_end_timestamp"] # TODO Make timezone aware
        event_instance = Event.objects.create(
            name=request.POST["event_name"],
            start_timestamp=start_timestamp,
            end_timestamp=end_timestamp
        )
        event_instance.save()
        return HttpResponseRedirect(reverse("appointer:event_detail", args=(event_instance.pk,)))
    else:
        return render(request, "appointer/add_event.html")

def delete_event(request: HttpRequest, event_id: int):
    event = get_object_or_404(Event, pk=event_id)
    event.delete()
    return HttpResponseRedirect(reverse("appointer:index"))

appointer/views/event_views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from appointer.models import Event


class EventDetailView(generic.DetailView):
    model = Event
    template_name = "appointer/event_detail.html"


def add_event(request: HttpRequest):
    if request.method == 'POST':
        print(request.POST["event_start_timestamp"])
        start_timestamp = request.POST["event_start_timestamp"] # TODO Make timezone aware
        end_timestamp = request.POST["event_end_timestamp"] # TODO Make timezone aware
        event_instance = Event.objects.create(
            name=request.POST["event_name"],
            start_timestamp=start_timestamp,
            end_timestamp=end_timestamp
        )
        event_instance.save()
        return HttpResponseRedirect(reverse("appointer:event_detail", args=(event_instance.pk,)))
    else:
        return render(request, "appointer/add_event.html")


def delete_event(request: HttpRequest, event_id: int):
    event = get_object_or_404(Event, pk=event_id)
    event.delete()
    return HttpResponseRedirect(reverse("appointer:index"))

appointer/views/signup_views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.urls import reverse

from appointer.models import Event, Signup


def signup(request: HttpRequest, event_id: int):
    event = get_object_or_404(Event, pk=event_id)
    name_in_form = request.POST["new_signup"]
    if not name_in_form.strip():
        return HttpResponseBadRequest(reason="No name provided")
    else:
        signup_instance = Signup(event=event, name=name_in_form)
        signup_instance.save()
        return HttpResponseRedirect(reverse("appointer:event_detail", args=(event.id,)))


def signout(request: HttpRequest, event_id: int, signout_id: int):
    event = get_object_or_404(Event, pk=event_id)

    signup_instance = Signup.objects.get(id=signout_id)
    signup_instance.delete()
    return HttpResponseRedirect(reverse("appointer:event_detail", args=(event.id,)))

appointer/views/views.py
from django.utils import timezone
from django.views import generic

from appointer.models import Event

class IndexView(generic.ListView):
    template_name = "appointer/index.html"
    context_object_name = "upcoming_events_list"

    def get_queryset(self):
        now = timezone.now()
        return Event.objects.filter(end_timestamp__gte=now).order_by("start_timestamp")[:5]

appointer/templates/appointer/add_event.html
<form action="{% url 'appointer:add_event' %}" method="post">
{% csrf_token %}
<fieldset>
  <legend><h1>Add event</h1></legend>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <label for="event_name">Event name:</label>
  <input type="text" id="event_name" name="event_name"><br />

  <label for="event_start_timestamp">Start timestamp:</label>
  <input type="datetime-local" id="event_start_timestamp" name="event_start_timestamp"><br />

  <label for="event_end_timestamp">End timestamp:</label>
  <input type="datetime-local" id="event_end_timestamp" name="event_end_timestamp"><br />

</fieldset>
<input type="submit" value="Create">
</form>

appointer/templates/appointer/event_detail.html
<fieldset>
    <legend><h1>{{ event.name }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <span>Start: {{ event.start_timestamp }}</span><br />
    <span>End: {{ event.end_timestamp }}</span>

    <ul>
        {% for signup in event.signup_set.all %}
            <li>
                <form action="{% url 'appointer:signout' event.id signup.id %}" method="post">
                    {% csrf_token %}
                    {{ signup.name }}
                    <input id="signout-btn" type="submit" value="Sign-Out" />
                </form>
            </li>
        {% endfor %}
    </ul>

    <form action="{% url 'appointer:signup' event.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="new_signup">
        <input type="submit" value="Sign up">
    </form>

    <form action="{% url 'appointer:delete_event' event.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Event">
    </form>

</fieldset>

appointer/templates/appointer/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'appointer/style.css' %}">

{% if upcoming_events_list %}
    <ul>
    {% for event in upcoming_events_list %}
        <li><a href="{% url 'appointer:event_detail' event.id %}">{{ event.name }} @ {{ event.start_timestamp }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No events are available.</p>
{% endif %}

<button type="button">
    <a href="{% url 'appointer:add_event' %}">Add event</a>
</button>